In [1]:
# CREATING OUR OWN NAIVE BAYES ALGORITHM

In [2]:
# FIRST WE WILL FIT THE MODEL AND THEN WE PREDICT IT
import numpy as np
import pandas as pd

In [3]:
# THIS IS FOR FIT FUNCTION
def fit(X_train,Y_train):
    #IT TAKES X_TRAIN AND Y_TRAIN AS PARAMETERS
    # WE WILL CREATE DICTIONARY TO STORE ALL THE CLASS AS KEYS , FEATUES AND ITS NAMES AS VALUES
    result={}
    # GET THE CLASSESS
    allclasses=set(Y_train)
    # THIS WILL PROVIDE YOU THE CLASS
    #ITERARE THROUGH THE CLASSES
    for class_ in allclasses:
        result[class_]={}
        # AGAIN CREATING THE DICTIONARY TO STORE THE FEATURES AS KEYS
        result['total_count']=len(Y_train)
        current_class=(Y_train==class_)
        X_train_current=X_train[current_class]
        Y_train_current=Y_train[current_class]
        # YOU ALSO HAVE TO STORE THE COUNT OF EACH CLASS ,CLASS MEANS THE OUTPUT VALUES[YES/NO]
        result[class_]['count']=len(Y_train_current)
        # NOW YOU HAVE TO GET ALL THE FEATURES FROM THAT
        allfeatures=X_train.shape[1]
        for j in range(1,allfeatures+1):
            result[class_][j]={}
            # TO STORE THE UNIQUE VALUE WHCIH WILL BE PRESENT IN THAT PARTICULAR FEATURE
            #NOW YOU GET THE NAMES OF THAT FEATURES
            allnames=set(X_train[:,j-1])
            # TRAVERSE THEOUGH THE NAME
            for name in allnames:
                result[class_][j][name]=(X_train_current[:,j-1]==name).sum()
                # YOU WILL STORE ALL THE NAMES IN THE DICTIOANRY
    return result


In [4]:
# NOW WE WILL WRITE CODE FOR PREDICT FUNCTION

In [5]:
# IN THIS WE ARE TAKING THE DICTIONARY AND WE ARE TAKING THE X_TEST

In [6]:
# NOW YOU WRITE THE FUNCTION FOR SINGLE PREDICTION /SINGLE TEST DATA PREDICTION
def single_point_prediction(dictionary,x,class_):
    output=dictionary[class_]['count']/dictionary['total_count']
    # YOU HAVE TO GET THE NUMBER OF FEATURES YOU CAN DO THAT IN TWO WAYS
    #numoffeatures=x.shape[-1]# WILL GIVE YOU THE NUMBER OF FEATURES
    numoffeatures=len(dictionary[class_].keys())-1
    # THIS WILL GIVE YOU THE FEATURES WHICH IS WITH THAT PARTICULAR CLASS
    # NOW ITERATE THROUGH THE LOOP
    for i in range(1,numoffeatures+1):
        # NOW YOU GET THE VALUES OR NAMES FROM THAT FEATURES
        xj=x[i-1]
        # THIS IS LAPLACE TRANSFORMATION TO AVOID ZERO PROBABILITIES
        counttt=dictionary[class_][i][xj]+1
        denomi=dictionary[class_]['count']+len(dictionary[class_][i].keys())
        answer=np.log(counttt)-np.log(denomi)
        # WE ARE USING LOG TO AVOID OUTPUT TO BECOME 0 IF IT HAS LOT MORE FEATURES IT HAS A TENDENCY TO BECOME ZERO
        output=output+answer
    return output

In [7]:
# NOW YOU ARE WRITING A FUNCTION TO PREDICT EACH DATA FROM X_TEST
def predictions(dictionary,x):
    # YOU HAVE TO GET ALL THE CLASSES FROM THE DICTIONARY [CLASSES MEANS  EX:YES/NO]
    classes=list(dictionary.keys())# YOU WILL GET ALL THE CLASSES
    bestprob=-10000
    bestclass=-1
    # WE WILL INITILIAZE BOTH BEST PROB AND BEST CLASS IN NEGATIVE VALUE BECAUSE PROB AND BEST CLASS CANNOT BE IN NEGATIVE
    firstrun=True
    # NOW YOU ITERATE THROUGH ALL THE CLASSESS
    for class_ in classes:
        # THIS WILL GIVE YOU 'total_count' as one of the class IF IT ENCOUNTERS JUST CONTINUE IT
        if class_=='total_count':
            continue
        bestclprob=single_point_prediction(dictionary,x,class_)
        if firstrun or bestclprob>bestprob:
            bestprob=bestclprob
            bestclass=class_
        firstrun=False
        # YOU HAVE DONE THE FIRST RUN SO TURN IT TO NEGATIVE
    # YOU RETURN WHATEVER BEST CLASS IT WILL GIVE YOU
    return bestclass

            
            

In [8]:
def predict(dictionary,X_test):
    # WE ARE STORING ALL THE BEST CLASS Y_PRED IN THE LISTS
    y_pred=[]
    # WE ARE TRAVERSING THROUGH EACH DATA OF THE DATASET
    for x in X_test:
        #print(x)
        # WE ARE CALLING ANOTHER PREDICT FUCNTION TO PREDICT EACH DATA
        best_Class=predictions(dictionary,x)
        y_pred.append(best_Class)
    # FINALLY WE ARE RETURNING Y_PRED WHICH HAS ALL THE PREDICTIONS
    return y_pred

In [9]:
def powerr(column):
    seco=column.mean()
    fi=0.5*seco
    ti=1.5*seco
    for i in range(0,len(column)):
        if column[i]<fi:
            column[i]=0
        elif column[i]<seco:
            column[i]=1
        elif column[i]<ti:
            column[i]=2
        else:
            column[i]=3
    return column

In [10]:
from sklearn import datasets
iris=datasets.load_iris()
X=iris.data
Y=iris.target

In [11]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
for i in range(X.shape[-1]):
    X[:,i]=powerr(X[:,i])

In [14]:
X

array([[1., 2., 0., 0.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 1., 0.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 2., 0., 0.],
       [1., 1., 0., 0.],
       [1., 2., 0., 0.],


In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

In [17]:
print(X_train)
print(Y_train)
print(X_test)
print(Y_test)

[[1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 1. 2. 3.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 1. 1. 1.]
 [2. 1. 2. 2.]
 [2. 2. 2. 3.]
 [2. 1. 2. 2.]
 [2. 2. 3. 3.]
 [1. 1. 2. 2.]
 [2. 1. 3. 3.]
 [1. 1. 2. 2.]
 [1. 2. 0. 0.]
 [2. 1. 3. 3.]
 [1. 1. 2. 1.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 1. 0.]
 [1. 1. 1. 1.]
 [2. 1. 2. 3.]
 [1. 2. 1. 0.]
 [1. 1. 0. 0.]
 [1. 2. 0. 0.]
 [1. 1. 2. 2.]
 [1. 2. 0. 0.]
 [1. 1. 2. 2.]
 [2. 2. 3. 3.]
 [1. 2. 0. 0.]
 [2. 1. 2. 2.]
 [1. 1. 2. 3.]
 [1. 2. 0. 0.]
 [2. 1. 2. 3.]
 [1. 1. 2. 3.]
 [2. 1. 2. 1.]
 [1. 1. 2. 2.]
 [2. 2. 2. 3.]
 [1. 1. 2. 2.]
 [1. 2. 0. 0.]
 [1. 1. 1. 1.]
 [2. 1. 2. 3.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 1. 2. 1.]
 [2. 1. 2. 2.]
 [1. 2. 0. 0.]
 [1. 1. 2. 3.]
 [1. 2. 0. 0.]
 [1. 2. 0. 1.]
 [2. 2. 2. 3.]
 [1. 1. 1. 1.]
 [2. 2. 3. 3.]
 [2. 1. 2. 2.]
 [2. 1. 2. 2.]
 [2. 1. 3. 3.]
 [1. 1. 2. 2.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [2. 1. 2. 2.]
 [2. 2. 3. 3.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 1. 0. 0.]
 [2. 1. 2. 2.]
 [2. 2. 2.

In [18]:
dictionary=fit(X_train,Y_train)

In [19]:
Y_pred=predict(dictionary,X_test)

In [20]:
print(Y_pred)

[1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0]


In [21]:
from sklearn.metrics import confusion_matrix,classification_report

In [22]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [23]:
print(confusion_matrix(Y_test,Y_pred))

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [24]:
# WE DONT HAVE ANY ERRORS,